{% set name = "github-pages-health-check" %}
{% set version = "1.17.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 15aef811ae9db1573cfb6e9c3145f7e23aa3e2747ac668c36c78da35bb2665e0

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-addressable >=2.3,<3
    - rb-dnsruby >=1.60,<2
    - rb-octokit >=4.0,<5
    - rb-public_suffix >=3.0,<4
    - rb-typhoeus >=1.3,<2

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.md
  summary: Checks your GitHub Pages site for commons DNS configuration issues

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/github/{{ name }}

extra:
  recipe-maintainers:
    - sodre
