travis:
  secure:
    BINSTAR_TOKEN: EYh0TpE0cBhlAvj0WJvP8jeF9TuHH2sA4hu+2G07+MRQcq+IZjXsMnBUz8Lwi5BOudWpopRYYHW56G4WXgGpzDMzyg6V9PyhJFzejtNU5pqDIigzpyVmFZ/Jc36ilp6R5NFmaa1oK9O7o9iLqvKxDar5oWdUI1Eh5E7TutMmIppoP0ItdG+HbOIEWvKBoZVV1W+jT8vBKuG566f7KF7N4fwtLT7JPlHVHO0WisWpNrxTJqNbvImIBv0GEs6ZebJ8E1iYrN3sqQbUj8/eky89ygCvoatVvBoK2qUFCpHx513sh06cTtlMyfm+zHA2p7CHB1r4GIQiIIAItOJ/jIo8AgKl24CnBkBAjV7+aI8QEYtuDVtNgkaYDy8VUbyiCMn6jG91QLB/oCAa+0DH1dNO5Ch4Tq5a8UNLrXNZaMPfrP3xpk6AWxWyuRRypW+7yF0LSCT0ONN6pLtLQ93nknwIKiBwJDWE0egSGKcHT/xfN79hk6a8cYl2xFuZSJ4DaVPbNMYDrMuAp5/fVboXIPb7rq+GnwaROpPT+h8tJXJlcOuQrUBs0lCGNNa0s4Cg2Mq5uyuWrLCyNQai/hJYK5ccHOQlDbq1G10ysQX+F3XXziZTBj0dKf/+B2uDrouxgVE6LOApPgVgnuDFSZUsVCwdVMPz7Ga0IMKbjAZZ+dCt7Eg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
